[31337]
endpoint_url = "http://127.0.0.1:8545"

[31337.string]
mnemonic = "math razor capable expose worth grape metal sunset metal sudden usage scheme"
port_cross = "cross"
mock_client_type = "mock-client"

[31337.uint]
mnemonic_index = 0

[31337.bool]
debug_mode = true

[31337.address]
ibc_handler = "0xC5777A1ac9A446aBDae4d4D71a330ebF77705a46"
mock_cross_contract = "0xff77D90D6aA12db33d3Ba50A34fB25401f6e4c4F"
cross_simple_module = "0xF938fE7482Fe4d1b3f84E28F1D6407836AA27d99"
tx_manager = "0x06e5dEB55CAffb1339fb447d860E305249EaD495"
mock_client = "0x72f25b3D42e279917b4bd9284c22b99cBe521076"
deployer = "0xa89F47C6b463f74d87572b058427dA0A13ec5425"
my_erc20 = "0x912911A4D64C3917E78C19531E4b0df9Db534938"
my_erc20_transfer_module = "0xBF346b5BC386c7C3378688286406B08E9327d312"

[31338]
endpoint_url = "http://127.0.0.1:8546"

[31338.string]
mnemonic = "math razor capable expose worth grape metal sunset metal sudden usage scheme"
port_cross = "cross"
mock_client_type = "mock-client"

[31338.uint]
mnemonic_index = 0

[31338.bool]
debug_mode = true

[31338.address]
ibc_handler = "0xC5777A1ac9A446aBDae4d4D71a330ebF77705a46"
mock_cross_contract = "0xff77D90D6aA12db33d3Ba50A34fB25401f6e4c4F"
cross_simple_module = "0xF938fE7482Fe4d1b3f84E28F1D6407836AA27d99"
tx_manager = "0x06e5dEB55CAffb1339fb447d860E305249EaD495"
mock_client = "0x72f25b3D42e279917b4bd9284c22b99cBe521076"
deployer = "0xa89F47C6b463f74d87572b058427dA0A13ec5425"
my_erc20 = "0x912911A4D64C3917E78C19531E4b0df9Db534938"
my_erc20_transfer_module = "0xBF346b5BC386c7C3378688286406B08E9327d312"
