[31337]
endpoint_url = "http://127.0.0.1:8545"

[31337.string]
mnemonic = "math razor capable expose worth grape metal sunset metal sudden usage scheme"
port_cross = "cross"
mock_client_type = "mock-client"

[31337.uint]
mnemonic_index = 0

[31337.bool]
debug_mode = true

[31337.address]
ibc_handler = "0xaa43d337145E8930d01cb4E60Abf6595C692921E"
mock_cross_contract = "0xff77D90D6aA12db33d3Ba50A34fB25401f6e4c4F"
cross_simple_module = "0x37978908bac82F0191b674235A0fEEE31e7524a4"
tx_manager = "0x87d7778dbc81251D5A0D78DFD8a0C359887E98C9"
mock_client = "0x173FFadd93aefC4F6e2D9bB20825E68A736DE047"
deployer = "0xa89F47C6b463f74d87572b058427dA0A13ec5425"
my_erc20 = "0xff77D90D6aA12db33d3Ba50A34fB25401f6e4c4F"
my_erc20_transfer_module = "0x2F5703804E29F4252FA9405B8D357220d11b3bd9"

[31338]
endpoint_url = "http://127.0.0.1:8546"

[31338.string]
mnemonic = "math razor capable expose worth grape metal sunset metal sudden usage scheme"
port_cross = "cross"
mock_client_type = "mock-client"

[31338.uint]
mnemonic_index = 0

[31338.bool]
debug_mode = true

[31338.address]
ibc_handler = "0xaa43d337145E8930d01cb4E60Abf6595C692921E"
mock_cross_contract = "0xff77D90D6aA12db33d3Ba50A34fB25401f6e4c4F"
cross_simple_module = "0x37978908bac82F0191b674235A0fEEE31e7524a4"
tx_manager = "0x87d7778dbc81251D5A0D78DFD8a0C359887E98C9"
mock_client = "0x173FFadd93aefC4F6e2D9bB20825E68A736DE047"
deployer = "0xa89F47C6b463f74d87572b058427dA0A13ec5425"
my_erc20 = "0xff77D90D6aA12db33d3Ba50A34fB25401f6e4c4F"
my_erc20_transfer_module = "0x2F5703804E29F4252FA9405B8D357220d11b3bd9"
