[profile.default]
solc_version = "0.8.30"
libs = ["lib", "node_modules"]
optimizer = true
optimizer_runs = 200
evm_version = "london"
fs_permissions = [
  { access = "read-write", path = "./deployments.toml" }
]
via_ir = true

remappings = [
  "src/proto/=node_modules/@datachainlab/cross-solidity/src/proto/"
]

[rpc_endpoints]
coordinator   = "http://127.0.0.1:8545"
participant   = "http://127.0.0.1:8546"
